/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuartzoRouteImport } from './routes/quartzo'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PedrasRouteImport } from './routes/pedras'
import { Route as MarmoreRouteImport } from './routes/marmore'
import { Route as MarmorariaRouteImport } from './routes/marmoraria'
import { Route as GranitoRouteImport } from './routes/granito'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BanheiroRouteImport } from './routes/banheiro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as PedrasSlugRouteImport } from './routes/pedras.$slug'
import { Route as MarmorariaCidadeRouteImport } from './routes/marmoraria.$cidade'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartzoRoute = QuartzoRouteImport.update({
  id: '/quartzo',
  path: '/quartzo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedrasRoute = PedrasRouteImport.update({
  id: '/pedras',
  path: '/pedras',
  getParentRoute: () => rootRouteImport,
} as any)
const MarmoreRoute = MarmoreRouteImport.update({
  id: '/marmore',
  path: '/marmore',
  getParentRoute: () => rootRouteImport,
} as any)
const MarmorariaRoute = MarmorariaRouteImport.update({
  id: '/marmoraria',
  path: '/marmoraria',
  getParentRoute: () => rootRouteImport,
} as any)
const GranitoRoute = GranitoRouteImport.update({
  id: '/granito',
  path: '/granito',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BanheiroRoute = BanheiroRouteImport.update({
  id: '/banheiro',
  path: '/banheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const PedrasSlugRoute = PedrasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PedrasRoute,
} as any)
const MarmorariaCidadeRoute = MarmorariaCidadeRouteImport.update({
  id: '/$cidade',
  path: '/$cidade',
  getParentRoute: () => MarmorariaRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banheiro': typeof BanheiroRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cozinha': typeof CozinhaRoute
  '/galeria': typeof GaleriaRoute
  '/granito': typeof GranitoRoute
  '/marmoraria': typeof MarmorariaRouteWithChildren
  '/marmore': typeof MarmoreRoute
  '/pedras': typeof PedrasRouteWithChildren
  '/precos': typeof PrecosRoute
  '/quartzo': typeof QuartzoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marmoraria/$cidade': typeof MarmorariaCidadeRoute
  '/pedras/$slug': typeof PedrasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banheiro': typeof BanheiroRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cozinha': typeof CozinhaRoute
  '/galeria': typeof GaleriaRoute
  '/granito': typeof GranitoRoute
  '/marmoraria': typeof MarmorariaRouteWithChildren
  '/marmore': typeof MarmoreRoute
  '/pedras': typeof PedrasRouteWithChildren
  '/precos': typeof PrecosRoute
  '/quartzo': typeof QuartzoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marmoraria/$cidade': typeof MarmorariaCidadeRoute
  '/pedras/$slug': typeof PedrasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banheiro': typeof BanheiroRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cozinha': typeof CozinhaRoute
  '/galeria': typeof GaleriaRoute
  '/granito': typeof GranitoRoute
  '/marmoraria': typeof MarmorariaRouteWithChildren
  '/marmore': typeof MarmoreRoute
  '/pedras': typeof PedrasRouteWithChildren
  '/precos': typeof PrecosRoute
  '/quartzo': typeof QuartzoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marmoraria/$cidade': typeof MarmorariaCidadeRoute
  '/pedras/$slug': typeof PedrasSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banheiro'
    | '/blog'
    | '/contato'
    | '/cozinha'
    | '/galeria'
    | '/granito'
    | '/marmoraria'
    | '/marmore'
    | '/pedras'
    | '/precos'
    | '/quartzo'
    | '/servicos'
    | '/sitemap'
    | '/blog/$slug'
    | '/marmoraria/$cidade'
    | '/pedras/$slug'
    | '/servicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banheiro'
    | '/blog'
    | '/contato'
    | '/cozinha'
    | '/galeria'
    | '/granito'
    | '/marmoraria'
    | '/marmore'
    | '/pedras'
    | '/precos'
    | '/quartzo'
    | '/servicos'
    | '/sitemap'
    | '/blog/$slug'
    | '/marmoraria/$cidade'
    | '/pedras/$slug'
    | '/servicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/banheiro'
    | '/blog'
    | '/contato'
    | '/cozinha'
    | '/galeria'
    | '/granito'
    | '/marmoraria'
    | '/marmore'
    | '/pedras'
    | '/precos'
    | '/quartzo'
    | '/servicos'
    | '/sitemap'
    | '/blog/$slug'
    | '/marmoraria/$cidade'
    | '/pedras/$slug'
    | '/servicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanheiroRoute: typeof BanheiroRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CozinhaRoute: typeof CozinhaRoute
  GaleriaRoute: typeof GaleriaRoute
  GranitoRoute: typeof GranitoRoute
  MarmorariaRoute: typeof MarmorariaRouteWithChildren
  MarmoreRoute: typeof MarmoreRoute
  PedrasRoute: typeof PedrasRouteWithChildren
  PrecosRoute: typeof PrecosRoute
  QuartzoRoute: typeof QuartzoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quartzo': {
      id: '/quartzo'
      path: '/quartzo'
      fullPath: '/quartzo'
      preLoaderRoute: typeof QuartzoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedras': {
      id: '/pedras'
      path: '/pedras'
      fullPath: '/pedras'
      preLoaderRoute: typeof PedrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marmore': {
      id: '/marmore'
      path: '/marmore'
      fullPath: '/marmore'
      preLoaderRoute: typeof MarmoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marmoraria': {
      id: '/marmoraria'
      path: '/marmoraria'
      fullPath: '/marmoraria'
      preLoaderRoute: typeof MarmorariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/granito': {
      id: '/granito'
      path: '/granito'
      fullPath: '/granito'
      preLoaderRoute: typeof GranitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banheiro': {
      id: '/banheiro'
      path: '/banheiro'
      fullPath: '/banheiro'
      preLoaderRoute: typeof BanheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/pedras/$slug': {
      id: '/pedras/$slug'
      path: '/$slug'
      fullPath: '/pedras/$slug'
      preLoaderRoute: typeof PedrasSlugRouteImport
      parentRoute: typeof PedrasRoute
    }
    '/marmoraria/$cidade': {
      id: '/marmoraria/$cidade'
      path: '/$cidade'
      fullPath: '/marmoraria/$cidade'
      preLoaderRoute: typeof MarmorariaCidadeRouteImport
      parentRoute: typeof MarmorariaRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface MarmorariaRouteChildren {
  MarmorariaCidadeRoute: typeof MarmorariaCidadeRoute
}

const MarmorariaRouteChildren: MarmorariaRouteChildren = {
  MarmorariaCidadeRoute: MarmorariaCidadeRoute,
}

const MarmorariaRouteWithChildren = MarmorariaRoute._addFileChildren(
  MarmorariaRouteChildren,
)

interface PedrasRouteChildren {
  PedrasSlugRoute: typeof PedrasSlugRoute
}

const PedrasRouteChildren: PedrasRouteChildren = {
  PedrasSlugRoute: PedrasSlugRoute,
}

const PedrasRouteWithChildren =
  PedrasRoute._addFileChildren(PedrasRouteChildren)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanheiroRoute: BanheiroRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CozinhaRoute: CozinhaRoute,
  GaleriaRoute: GaleriaRoute,
  GranitoRoute: GranitoRoute,
  MarmorariaRoute: MarmorariaRouteWithChildren,
  MarmoreRoute: MarmoreRoute,
  PedrasRoute: PedrasRouteWithChildren,
  PrecosRoute: PrecosRoute,
  QuartzoRoute: QuartzoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
